// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c6455f4e-55d7-4fb9-acd3-04dffe85b3ad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Tg4rSmFBq",
    "aws_user_pools_web_client_id": "2a9gadnoklsni592mdfrfan1q6",
    "oauth": {
        "domain": "openlearn8c0bb80d-8c0bb80d-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
